Add TTS
Vrabbers/bnbnav-net-client pull request #24
Opened 2023-02-01 03:25 UTC by Royce551

Still needs implementations for other platforms

2023-02-01 03:41 UTC, vicr123 requested changes
Looks good but can we get locale support in before this gets merged?

2023-02-01 03:52 UTC, vicr123 requested changes
We should make the culture a global thing - it doesn't make sense to constantly pass it to the speech function when the application language only changes on restart.

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/WindowsTextToSpeechProvider.cs
> +    public Task SpeakAsync(string text, CultureInfo culture)
```suggestion
    public Task SpeakAsync(string text)
```

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/WindowsTextToSpeechProvider.cs
> +
```suggestion

public CultureInfo Culture { get; set; }

```

We should make the culture a global thing

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/ITextToSpeechProvider.cs
> +}
```suggestion
    public CultureInfo Culture { get; set; }
}
```

Make the culture a global thing

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/DummyTextToSpeechProvider.cs
> +}
```suggestion
    public CultureInfo Culture { get; set; }
}
```

Make the culture a global thing

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/DummyTextToSpeechProvider.cs
> +using System.Threading.Tasks;
```suggestion
using System.Globalization;
using System.Threading.Tasks;
```

Clean up imports

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/AppBuilderExtensions.cs
> +
```suggestion
```

Clean up imports

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/ITextToSpeechProvider.cs
> +
```suggestion
using System.Globalization;
using System.Threading.Tasks;
```

Clean up imports

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/WindowsTextToSpeechProvider.cs
> +using System.Threading.Tasks;
```suggestion
using System;
using System.Globalization;
using System.Speech.Synthesis;
using System.Threading.Tasks;
```

Clean up imports

2023-02-01 03:52 UTC, vicr123 commented on BnbnavNetClient/Services/TextToSpeech/WindowsTextToSpeechProvider.cs
> +        var prompt = new PromptBuilder(culture);
```suggestion
        var prompt = new PromptBuilder(Culture);
```

Make the culture a global thing

2023-02-01 05:02 UTC, Vrabbers requested changes
Either use a global culture property, or perhaps utilize ``CultureInfo.CurrentUICulture`` directly, as that will have the value of the text in it already

2023-02-04 09:56 UTC, vicr123 requested changes
'REQUEST_CHANGES' performed by Xcode.

2023-02-04 15:11 UTC, vicr123 approved these changes
'APPROVE' performed by Xcode.

2023-02-04 15:12 UTC, merged